apiVersion: v1
kind: Service
metadata:
  name: teamflow-redis-service
  namespace: teamflow-namespace
spec:
  selector:
    app: teamflow-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
