version: '3'

services:
  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    container_name: teamflow-celery
    volumes:
      - .:/app
    env_file:
      - .env
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "7000:7000"
    volumes:
      - .:/app
    depends_on:
      - celery
    container_name: teamflow
    env_file:
      - .env
