services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - "5432:5432"
    container_name: teamflow-postgres
    volumes:
      - .:/app
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7000:7000"
    volumes:
      - .:/app
    depends_on:
      - db
    container_name: teamflow
    env_file:
      - .env
