services:
  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    container_name: teamflow-celery
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      - teamflow_network
    volumes:
      - .:/app
    env_file:
      - .env
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "7000:7000"
    volumes:
      - .:/app
    depends_on:
      - redis
      - celery
    container_name: teamflow-api
    networks:
      - teamflow_network
    env_file:
      - .env
  redis:
    image: redis:7.0-alpine
    restart: unless-stopped
    container_name: teamflow-redis
    command: --port 6380
    expose:
      - 6380
    networks:
      - teamflow_network
    ports:
      - 6380:6380

  nginx:
    image: nginx:latest
    container_name: teamflow-nginx
    ports:
      - "80:80"
    depends_on:
      - api
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - teamflow_network

networks:
  teamflow_network:
    external: true
