apiVersion: v1
kind: Service
metadata:
  name: teamflow-api-service
  namespace: teamflow-namespace
spec:
  selector:
    app: teamflow-api
  ports:
    - protocol: TCP
      port: 7000
      targetPort: 7000
  type: NodePort
