apiVersion: apps/v1
kind: Deployment
metadata:
  name: teamflow-api
  namespace: teamflow-namespace
  labels:
    app: teamflow-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: teamflow-api
  template:
    metadata:
      labels:
        app: teamflow-api
    spec:
      containers:
        - name: teamflow-api
          image: engrmarkk/teamflow-api:latest
          ports:
            - containerPort: 7000
          envFrom:
            - configMapRef:
                name: teamflow-config
            - secretRef:
                name: teamflow-secret
