apiVersion: v1
kind: Service
metadata:
  name: teamflow-postgres-service
  namespace: teamflow-namespace
spec:
  selector:
    app: teamflow-postgres
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
  type: NodePort
